module.exports = {
  list: [
    {
      name: 'Link',
      title: '链接',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-link","destructuring":0}',
      props:
        '[{"type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"label":"href","name":"href","description":"跳转目标地址"},{"label":"miniappHref","name":"miniappHref","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性","description":"跳转类型:跳转地址，例如 navigate:/pages/index/index"},{"label":"onLoad","name":"onLoad","type":"Function","category":"基础属性"},{"label":"onPress","name":"onPress","type":"Function","category":"基础属性","description":"节点被点击之后触发"}]',
      version: '0.0.0',
      code: null,
      basicId: 1209,
      versionId: 2805,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.1',
      items: []
    },
    {
      name: 'Text',
      title: '文本',
      screenshot:
        'https://img.alicdn.com/tfs/TB1Bo3iiVY7gK0jSZKzXXaikpXa-192-144.png_300x300Q90.jpg',
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'Rax Text',
      dependence: '{"package":"rax-text","destructuring":0}',
      props:
        '[{"label":"行数","name":"numberOfLines","type":"Mixin","description":"行数","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"_key":1},{"label":"文案","name":"text","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性","_key":2}]',
      version: '0.0.0',
      code: '',
      basicId: 1021,
      versionId: 2204,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.6',
      items: []
    },
    {
      name: 'Canvas',
      title: 'Canvas',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'Canvas',
      dependence: '{"package":"rax-canvas","destructuring":0}',
      props:
        '[{"label":"className","name":"className","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"width","name":"width","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"height","name":"height","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"onClick","name":"onClick","type":"Function","category":"基础属性"},{"label":"onLongPress","name":"onLongPress","type":"Function","category":"基础属性"},{"label":"onTouchStart","name":"onTouchStart","type":"Function","category":"基础属性"},{"label":"onTouchMove","name":"onTouchMove","type":"Function","category":"基础属性"},{"label":"onTouchEnd","name":"onTouchEnd","type":"Function","category":"基础属性"},{"label":"onTouchCancel","name":"onTouchCancel","type":"Function","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1035,
      versionId: 2218,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.0.0',
      items: []
    },
    {
      name: 'Modal',
      title: 'Modal 提供了弹出遮罩层的能力',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-modal","destructuring":0}',
      props:
        '[{"label":"visible","name":"visible","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"contentStyle","name":"contentStyle","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"maskStyle","name":"maskStyle","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"onShow","name":"onShow","type":"Function","category":"基础属性"},{"label":"onHide","name":"onHide","type":"Function","category":"基础属性"},{"label":"maskCanBeClick","name":"maskCanBeClick","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"delay","name":"delay","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"duration","name":"duration","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1038,
      versionId: 2221,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.2.3',
      items: []
    },
    {
      name: 'Waterfall',
      title: '用于实现瀑布流的列表容器',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-waterfall","destructuring":0}',
      props:
        '[{"label":"dataSource","name":"dataSource","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"renderItem","name":"renderItem","type":"Function","category":"基础属性"},{"label":"renderHeader","name":"renderHeader","type":"Function","category":"基础属性"},{"label":"renderFooter","name":"renderFooter","type":"Function","category":"基础属性"},{"label":"columnWidth","name":"columnWidth","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"columnCount","name":"columnCount","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"columnGap","name":"columnGap","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"cellProps","name":"cellProps","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"onEndReachedThreshold","name":"onEndReachedThreshold","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"onEndReached","name":"onEndReached","type":"Function","category":"基础属性"},{"label":"leftGap","name":"leftGap","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"rightGap","name":"rightGap","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1032,
      versionId: 2215,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.0',
      items: []
    },
    {
      name: 'RefreshControl',
      title: '滚动容器的下拉刷新功能',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-refreshcontrol","destructuring":0}',
      props:
        '[{"label":"refreshing","name":"refreshing","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"onRefresh","name":"onRefresh","type":"Function","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1036,
      versionId: 2219,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.0',
      items: []
    },
    {
      name: 'Embed',
      title: '内嵌内容容器',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-embed","destructuring":0}',
      props:
        '[{"label":"src","name":"src","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"urlParam","name":"urlParam","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"page_inside_embed","name":"page_inside_embed","type":"Mixin","category":"基础属性","props":{"types":["Switch","Expression"],"defaultType":"Switch"}},{"label":"page_home_isweex","name":"page_home_isweex","type":"Mixin","category":"基础属性","props":{"types":["Switch","Expression"],"defaultType":"Switch"}}]',
      version: '0.0.0',
      code: '{"componentName":"Component","fileName":"Embed","props":{},"children":[]}',
      basicId: 1033,
      versionId: 2216,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.0',
      items: []
    },
    {
      name: 'RecyclerView',
      title: '动态 View 的滚动组件',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: '动态 View 的滚动组件',
      dependence: '{"package":"rax-recyclerview","destructuring":0}',
      props:
        '[{"label":"onEndReachedThreshold","name":"onEndReachedThreshold","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"onEndReached","name":"onEndReached","type":"Function","category":"基础属性"},{"label":"onScroll","name":"onScroll","type":"Function","category":"基础属性"},{"label":"itemSize","name":"itemSize","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"totalSize","name":"totalSize","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1031,
      versionId: 2214,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.3',
      items: []
    },
    {
      name: 'ScrollView',
      title: '滚动容器',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-scrollview","destructuring":0}',
      props:
        '[{"label":"scrollEventThrottle","name":"scrollEventThrottle","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"horizontal","name":"horizontal","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"showsHorizontalScrollIndicator","name":"showsHorizontalScrollIndicator","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"showsVerticalScrollIndicator","name":"showsVerticalScrollIndicator","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"onEndReachedThreshold","name":"onEndReachedThreshold","type":"NumberPicker","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"onEndReached","name":"onEndReached","type":"Function","category":"基础属性"},{"label":"onScroll","name":"onScroll","type":"Function","category":"基础属性"},{"label":"onTouchStart","name":"onTouchStart","type":"Function","category":"基础属性"},{"label":"onTouchMove","name":"onTouchMove","type":"Function","category":"基础属性"},{"label":"onTouchEnd","name":"onTouchEnd","type":"Function","category":"基础属性"},{"label":"onTouchCancel","name":"onTouchCancel","type":"Function","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1030,
      versionId: 2213,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.0.0',
      items: []
    },
    {
      name: 'Icon',
      title: '图标',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'Rax 图标组件',
      dependence: '{"package":"rax-icon","destructuring":0}',
      props:
        '[{"label":"source","name":"source","type":"Mixin","category":"基础属性","props":{"types":["ObjectButton","Expression"],"defaultType":"ObjectButton","objectButtonProps":{"width":600,"formProps":{"labelCol":{"span":6},"wrapperCol":{"span":16}},"children":[{"componentName":"FormItem","props":{"name":"uri","label":"icon uri","help":"设置icon的 uri"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]},{"componentName":"FormItem","props":{"name":"codePoint","label":"iconfont的码点","help":"设置iconfont的码点"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]}]}},"description":"当 icon 是图片时，uri 是图片路径，优先级比 fontFamily 和 codePoint 高"},{"label":"fontFamily","name":"fontFamily","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"description":"iconfont的字体"}]',
      version: '0.0.0',
      code: '{"componentName":"Component","fileName":"Icon","props":{},"children":[]}',
      basicId: 1026,
      versionId: 2209,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.2',
      items: []
    },
    {
      name: 'Video',
      title: '视频播放',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-video","destructuring":0}',
      props: '[]',
      version: '0.0.0',
      code: '',
      basicId: 1029,
      versionId: 2212,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.2',
      items: []
    },
    {
      name: 'TextInput',
      title: '富文本',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'TextInput 是唤起用户键盘的基础组件',
      dependence: '{"package":"rax-textinput","destructuring":0}',
      props:
        '[{"label":"multiline","name":"multiline","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"autoComplete","name":"autoComplete","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"autoFocus","name":"autoFocus","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"editable","name":"editable","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"keyboardType","name":"keyboardType","type":"Mixin","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"default","value":"default"},{"label":"ascii-capable","value":"ascii-capable"},{"label":"numbers-and-punctuation","value":"numbers-and-punctuation"},{"label":"number-pad","value":"number-pad"},{"label":"phone-pad","value":"phone-pad"},{"label":"name-phone-pad","value":"name-phone-pad"},{"label":"email-address","value":"email-address"},{"label":"decimal-pad","value":"decimal-pad"},{"label":"twitter","value":"twitter"},{"label":"web-search","value":"web-search"},{"label":"numeric","value":"numeric"}]}},"category":"基础属性"},{"label":"maxLength","name":"maxLength","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"maxNumberOfLines","name":"maxNumberOfLines","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"numberOfLines","name":"numberOfLines","type":"Mixin","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"},"category":"基础属性"},{"label":"placeholder","name":"placeholder","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"placeholderColor","name":"placeholderColor","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"password","name":"password","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"secureTextEntry","name":"secureTextEntry","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"value","name":"value","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"defaultValue","name":"defaultValue","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性"},{"label":"confirmType","name":"confirmType","type":"Mixin","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"完成","value":"done"},{"label":"前往","value":"go"},{"label":"下一个","value":"next"},{"label":"搜索","value":"search"},{"label":"发送","value":"send"}]}},"category":"基础属性"},{"label":"enableNative","name":"enableNative","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"fixed","name":"fixed","type":"Mixin","props":{"types":["Switch","Expression"],"defaultType":"Switch"},"category":"基础属性"},{"label":"onChange","name":"onChange","type":"Function","props":{},"category":"基础属性"},{"label":"onChangeText","name":"onChangeText","type":"Function","category":"基础属性"},{"label":"onFocus","name":"onFocus","type":"Function","category":"基础属性"},{"label":"onBlur","name":"onBlur","type":"Function","category":"基础属性"},{"label":"onInput","name":"onInput","type":"Function","props":{},"category":"基础属性"},{"label":"onConfirm","name":"onConfirm","type":"Function","props":{},"category":"基础属性"},{"label":"onAppear","name":"onAppear","type":"Function","props":{},"category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1023,
      versionId: 2206,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.8',
      items: []
    },
    {
      name: 'Image',
      title: '图片',
      screenshot:
        'https://img.alicdn.com/tfs/TB1SnwliYr1gK0jSZR0XXbP8XXa-192-144.png_300x300Q90.jpg',
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'Rax 图片组件',
      dependence: '{"package":"rax-image","destructuring":0}',
      props:
        '[{"label":"source","name":"source","type":"Mixin","description":"设置图片的 uri","category":"基础属性","props":{"types":["ObjectButton","Expression"],"defaultType":"ObjectButton","objectButtonProps":{"width":600,"formProps":{"labelCol":{"span":6},"wrapperCol":{"span":16}},"children":[{"componentName":"FormItem","props":{"name":"uri","label":"图片 uri","help":"设置图片的 uri"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]}]}}},{"label":"fallbackSource","name":"fallbackSource","type":"Mixin","props":{"types":["ObjectButton","Expression"],"defaultType":"ObjectButton","objectButtonProps":{"width":600,"formProps":{"labelCol":{"span":6},"wrapperCol":{"span":16}},"children":[{"componentName":"FormItem","props":{"name":"uri","label":"图片 uri","help":"设置图片的 uri"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]}]}},"description":"备用图片的 uri（当主图加载失败是加载）\\t","category":"基础属性"},{"label":"resizeMode","name":"resizeMode","type":"Mixin","description":"当组件尺寸和图片尺寸不成比例的时候如何调整图片的大小","category":"基础属性","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"contain","value":"contain"},{"label":"cover","value":"cover"},{"label":"stretch","value":"stretch"}]}}},{"label":"mode","name":"mode","type":"Mixin","description":"小程序中的图片模式，可选项更多\\t","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"quality","name":"quality","type":"Mixin","description":"图片质量\\t","category":"基础属性","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"original","value":"original"},{"label":"normal","value":"normal"},{"label":"low","value":"low"},{"label":"high","value":"high"},{"label":"auto","value":"auto"}]}}},{"label":"placeholder","name":"placeholder","type":"Mixin","description":"占位图的 uri，在图片下载过程中将展示占位图，图片下载完成后将显示source中指定的图片。","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"onLoad","name":"onLoad","type":"Function","description":"图片加载成功的回调函数\\t","category":"基础属性"},{"label":"onError","name":"onError","type":"Function","description":"图片加载失败的回调函数\\t","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1027,
      versionId: 2210,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.0.4',
      items: []
    },
    {
      name: 'View',
      title: '视图',
      screenshot:
        'https://img.alicdn.com/tfs/TB1W1kki1L2gK0jSZPhXXahvXXa-192-144.png_300x300Q90.jpg',
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-view","destructuring":0}',
      props:
        '[{"type":"Function","category":"基础属性","label":"onLongPress","name":"onLongPress","description":"当组件被长按时触发的事件\\t"},{"label":"onAppear","name":"onAppear","type":"Function","description":"当组件在视窗内可见时触发的事件","category":"基础属性"},{"label":"onDisappear","name":"onDisappear","type":"Function","description":"当组件在视窗内消失时触发的事件","category":"基础属性"},{"label":"onTouchStart","name":"onTouchStart","type":"Function","description":"触摸到组件时触发的事件","category":"基础属性"},{"label":"onTouchMove","name":"onTouchMove","type":"Function","description":"手指在组件上移动时触发的事件\\t","category":"基础属性"},{"label":"onTouchEnd","name":"onTouchEnd","type":"Function","description":"触摸动作结束时触发的事件\\t","category":"基础属性"},{"label":"onTouchCancel","name":"onTouchCancel","type":"Function","description":"触摸动作被打断，如来电提醒，弹窗\\t","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1022,
      versionId: 2205,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.0',
      items: []
    },
    {
      name: 'PuiSubscribeCard',
      title: '订阅',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"@ali/puicom-rax-search-subscribe-card","destructuring":0}',
      props:
        '[{"label":"keys","name":"keys","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"object","placeholder":"[\\n\\t\\n]"}},"_key":1},{"label":"config","name":"config","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"object","placeholder":"{\\n\\t\\n}"}},"_key":2},{"label":"title","name":"title","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"_key":3},{"label":"提示文案","name":"toast","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"object","placeholder":"{\\n\\t\\n}"}},"_key":4},{"label":"添加图标","name":"plusIconUrl","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"_key":5},{"label":"删除图标","name":"delIconUrl","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"_key":6},{"label":"otherSubProps","name":"otherSubProps","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"object","placeholder":"{\\n\\t\\n}"}},"_key":7},{"label":"styles","name":"styles","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"object","placeholder":"{\\n\\t\\n}"}},"_key":8}]',
      version: '0.0.0',
      code: null,
      basicId: 1213,
      versionId: 2816,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 59,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.7',
      items: []
    },
    {
      name: 'PuiTab',
      title: '选项卡',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"@ali/puicom-rax-tab","destructuring":0}',
      props:
        '[{"label":"data","name":"data","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"object","placeholder":"[\\n\\t\\n]"}}},{"label":"默认选中","name":"defaultSelected","type":"Mixin","category":"基础属性","props":{"types":["Switch","Expression"],"defaultType":"Switch"}},{"label":"是否滚动","name":"isScroll","type":"Mixin","category":"基础属性","props":{"types":["Switch","Expression"],"defaultType":"Switch"}},{"label":" Tab宽度","name":"width","type":"Mixin","category":"基础属性","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"}},{"label":"单项宽度","name":"itemWidth","type":"Mixin","category":"基础属性","props":{"types":["NumberPicker","Expression"],"defaultType":"NumberPicker"}},{"label":"renderItem","name":"renderItem","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"function","placeholder":"function onSelect(e){\\n\\t\\n}"}}},{"label":"onSelect","name":"onSelect","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"function","placeholder":"function onSelect(e){\\n\\t\\n}"}}}]',
      version: '0.0.0',
      code: null,
      basicId: 1214,
      versionId: 2825,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 59,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.2',
      items: []
    },
    {
      name: 'PuiLink',
      title: '链接',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-link","destructuring":0}',
      props: null,
      version: '0.0.0',
      code: null,
      basicId: 1208,
      versionId: 2804,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 59,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.1',
      items: []
    },
    {
      name: 'PuiCategorySelect',
      title: '类目选择',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"@ali/puicom-rax-category-select","destructuring":0}',
      props:
        '[{"label":"主题","name":" theme","type":"Mixin","category":"基础属性","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"sf","value":"sf"},{"label":"zc","value":"zc"}]}}},{"label":"选中值","name":"filterValue","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"搜索 key","name":"filterKey","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"默认值","name":"defaultValue","type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"数据源","name":"dataSource","type":"Mixin","category":"基础属性","props":{"types":["MonacoEditor","Expression"],"defaultType":"MonacoEditor","monacoEditorProps":{"type":"button","language":"object","placeholder":"[\\n\\t\\n]"}}}]',
      version: '0.0.0',
      code: null,
      basicId: 1135,
      versionId: 2555,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 59,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.5',
      items: []
    }
  ],
  appList: []
};
