/**
 *     name: string; packageName: string; dependenceVersion: string; dependence: string, exportName: string;
    subName: string;
 */

export default {
  list: [
    {
      name: 'Link',
      title: '链接',
      screenshot: null,
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-link","destructuring":0}',
      props:
        '[{"type":"Mixin","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"label":"href","name":"href","description":"跳转目标地址"},{"label":"miniappHref","name":"miniappHref","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性","description":"跳转类型:跳转地址，例如 navigate:/pages/index/index"},{"label":"onLoad","name":"onLoad","type":"Function","category":"基础属性"},{"label":"onPress","name":"onPress","type":"Function","category":"基础属性","description":"节点被点击之后触发"}]',
      version: '0.0.0',
      code: null,
      basicId: 1209,
      versionId: 2805,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.1',
      items: []
    },
    {
      name: 'Text',
      title: '文本',
      screenshot:
        'https://img.alicdn.com/tfs/TB1Bo3iiVY7gK0jSZKzXXaikpXa-192-144.png_300x300Q90.jpg',
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'Rax Text',
      dependence: '{"package":"rax-text","destructuring":0}',
      props:
        '[{"label":"行数","name":"numberOfLines","type":"Mixin","description":"行数","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"},"_key":1},{"label":"文案","name":"text","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"},"category":"基础属性","_key":2}]',
      version: '0.0.0',
      code: '',
      basicId: 1021,
      versionId: 2204,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.6',
      items: []
    },
   
    {
      name: 'Image',
      title: '图片',
      screenshot:
        'https://img.alicdn.com/tfs/TB1SnwliYr1gK0jSZR0XXbP8XXa-192-144.png_300x300Q90.jpg',
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'Rax 图片组件',
      dependence: '{"package":"rax-image","destructuring":0}',
      props:
        '[{"label":"source","name":"source","type":"Mixin","description":"设置图片的 uri","category":"基础属性","props":{"types":["ObjectButton","Expression"],"defaultType":"ObjectButton","objectButtonProps":{"width":600,"formProps":{"labelCol":{"span":6},"wrapperCol":{"span":16}},"children":[{"componentName":"FormItem","props":{"name":"uri","label":"图片 uri","help":"设置图片的 uri"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]}]}}},{"label":"fallbackSource","name":"fallbackSource","type":"Mixin","props":{"types":["ObjectButton","Expression"],"defaultType":"ObjectButton","objectButtonProps":{"width":600,"formProps":{"labelCol":{"span":6},"wrapperCol":{"span":16}},"children":[{"componentName":"FormItem","props":{"name":"uri","label":"图片 uri","help":"设置图片的 uri"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]}]}},"description":"备用图片的 uri（当主图加载失败是加载）\\t","category":"基础属性"},{"label":"resizeMode","name":"resizeMode","type":"Mixin","description":"当组件尺寸和图片尺寸不成比例的时候如何调整图片的大小","category":"基础属性","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"contain","value":"contain"},{"label":"cover","value":"cover"},{"label":"stretch","value":"stretch"}]}}},{"label":"mode","name":"mode","type":"Mixin","description":"小程序中的图片模式，可选项更多\\t","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"quality","name":"quality","type":"Mixin","description":"图片质量\\t","category":"基础属性","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"original","value":"original"},{"label":"normal","value":"normal"},{"label":"low","value":"low"},{"label":"high","value":"high"},{"label":"auto","value":"auto"}]}}},{"label":"placeholder","name":"placeholder","type":"Mixin","description":"占位图的 uri，在图片下载过程中将展示占位图，图片下载完成后将显示source中指定的图片。","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"onLoad","name":"onLoad","type":"Function","description":"图片加载成功的回调函数\\t","category":"基础属性"},{"label":"onError","name":"onError","type":"Function","description":"图片加载失败的回调函数\\t","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1027,
      versionId: 2210,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.0.4',
      items: []
    },
    {
      name: 'Picture',
      title: '复杂的图片组件',
      screenshot:
        'https://img.alicdn.com/tfs/TB1SnwliYr1gK0jSZR0XXbP8XXa-192-144.png_300x300Q90.jpg',
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: 'Rax 图片组件',
      dependence: '{"package":"rax-picture","destructuring":0}',
      props:
        '[{"label":"source","name":"source","type":"Mixin","description":"设置图片的 uri","category":"基础属性","props":{"types":["ObjectButton","Expression"],"defaultType":"ObjectButton","objectButtonProps":{"width":600,"formProps":{"labelCol":{"span":6},"wrapperCol":{"span":16}},"children":[{"componentName":"FormItem","props":{"name":"uri","label":"图片 uri","help":"设置图片的 uri"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]}]}}},{"label":"fallbackSource","name":"fallbackSource","type":"Mixin","props":{"types":["ObjectButton","Expression"],"defaultType":"ObjectButton","objectButtonProps":{"width":600,"formProps":{"labelCol":{"span":6},"wrapperCol":{"span":16}},"children":[{"componentName":"FormItem","props":{"name":"uri","label":"图片 uri","help":"设置图片的 uri"},"children":[{"componentName":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]}]}},"description":"备用图片的 uri（当主图加载失败是加载）\\t","category":"基础属性"},{"label":"resizeMode","name":"resizeMode","type":"Mixin","description":"当组件尺寸和图片尺寸不成比例的时候如何调整图片的大小","category":"基础属性","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"contain","value":"contain"},{"label":"cover","value":"cover"},{"label":"stretch","value":"stretch"}]}}},{"label":"mode","name":"mode","type":"Mixin","description":"小程序中的图片模式，可选项更多\\t","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"quality","name":"quality","type":"Mixin","description":"图片质量\\t","category":"基础属性","props":{"types":["Select","Expression"],"defaultType":"Select","selectProps":{"hasClear":true,"dataSource":[{"label":"original","value":"original"},{"label":"normal","value":"normal"},{"label":"low","value":"low"},{"label":"high","value":"high"},{"label":"auto","value":"auto"}]}}},{"label":"placeholder","name":"placeholder","type":"Mixin","description":"占位图的 uri，在图片下载过程中将展示占位图，图片下载完成后将显示source中指定的图片。","category":"基础属性","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"label":"onLoad","name":"onLoad","type":"Function","description":"图片加载成功的回调函数\\t","category":"基础属性"},{"label":"onError","name":"onError","type":"Function","description":"图片加载失败的回调函数\\t","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1027,
      versionId: 2210,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.2.1',
      items: []
    },
    {
      name: 'View',
      title: '视图',
      screenshot:
        'https://img.alicdn.com/tfs/TB1W1kki1L2gK0jSZPhXXahvXXa-192-144.png_300x300Q90.jpg',
      icon: null,
      tags: null,
      package: null,
      destructuring: null,
      main: null,
      description: null,
      dependence: '{"package":"rax-view","destructuring":0}',
      props:
        '[{"type":"Function","category":"基础属性","label":"onLongPress","name":"onLongPress","description":"当组件被长按时触发的事件\\t"},{"label":"onAppear","name":"onAppear","type":"Function","description":"当组件在视窗内可见时触发的事件","category":"基础属性"},{"label":"onDisappear","name":"onDisappear","type":"Function","description":"当组件在视窗内消失时触发的事件","category":"基础属性"},{"label":"onTouchStart","name":"onTouchStart","type":"Function","description":"触摸到组件时触发的事件","category":"基础属性"},{"label":"onTouchMove","name":"onTouchMove","type":"Function","description":"手指在组件上移动时触发的事件\\t","category":"基础属性"},{"label":"onTouchEnd","name":"onTouchEnd","type":"Function","description":"触摸动作结束时触发的事件\\t","category":"基础属性"},{"label":"onTouchCancel","name":"onTouchCancel","type":"Function","description":"触摸动作被打断，如来电提醒，弹窗\\t","category":"基础属性"}]',
      version: '0.0.0',
      code: '',
      basicId: 1022,
      versionId: 2205,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      siteId: 27,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.0',
      items: []
    },
   
  ]
};
